### ISSUE TITLE
Matrix representation for many-body Hamiltonian

### ISSUE THREAD

**Issue by AQ1998** [Quantum-Many-Body/ExactDiagonalization.jl#5]
I wonder if there is any way to obtain matrix representation in a specific symmetric sector, e.g., k=0, p=1, for some many-body Hamiltonian with this package?

**Comment by waltergu** [comment]
Particle number and spin-z component conservation are supported. Translation symmetry is not.

**Comment by waltergu** [comment]
> I wonder if there is any way to obtain matrix representation in a specific symmetric sector, e.g., k=0, p=1, for some many-body Hamiltonian with this package?

Particle number and spin-z component conservation are supported. Translation symmetry is not.
